In [8]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import matplotlib.pyplot as plt
import seaborn as sns
import os
from os.path import join as pjoin
import datetime

In [9]:
data_root = './input'

In [10]:
def load_data(data='train',n=2):
    df = pd.DataFrame()
    for i in range(n) :
        if data=='train':
            if i > 8 :
                break
            dfpart = pd.read_pickle(pjoin(data_root,f'train_{i}.pkl'))
        elif data=='test':
            if i > 2 :
                break
            dfpart = pd.read_pickle(pjoin(data_root,f'test_{i}.pkl'))
        df = pd.concat([df,dfpart])
        del dfpart
    return df

In [11]:
df_train = load_data(n=9)

In [12]:
df_train.head()

  channelGrouping       date         ...         Date_Is_year_end  Date_Is_year_start
0  Organic Search 2017-10-16         ...                    False               False
1        Referral 2017-10-16         ...                    False               False
2          Direct 2017-10-16         ...                    False               False
3  Organic Search 2017-10-16         ...                    False               False
4  Organic Search 2017-10-16         ...                    False               False

[5 rows x 53 columns]

In [17]:
df_train[df_train['fullVisitorId']=='7813149961404844386'].sort_values(by='visitNumber')[['date', 'visitId', 'visitNumber', 'totals_hits', 'totals_pageviews', 'totals_transactionRevenue']].head(20)

             date     visitId            ...              totals_pageviews  totals_transactionRevenue
114476 2016-11-17  1479408977            ...                            33                  7190000.0
31816  2016-11-18  1479496350            ...                             2                        0.0
32524  2016-11-18  1479507825            ...                            12                 51990000.0
138140 2016-11-22  1479831970            ...                             3                        0.0
138305 2016-11-22  1479842287            ...                             4                        0.0
95433  2016-12-02  1480691778            ...                             1                        0.0
3329   2016-12-06  1481036817            ...                            10                  8990000.0
4477   2016-12-06  1481040342            ...                             1                        0.0
3514   2016-12-06  1481061263            ...                            19                        0.0
3516   2016-12-06  1481065071            ...                            26                        0.0
121418 2016-12-09  1481296334            ...                             2                        0.0
119960 2016-12-09  1481302820            ...                             6                        0.0
121393 2016-12-09  1481305812            ...                             2                        0.0
121430 2016-12-09  1481308967            ...                             2                        0.0
121497 2016-12-09  1481311109            ...                             3                        0.0
158231 2016-12-12  1481563972            ...                             3                        0.0
93009  2016-12-14  1481747552            ...                            17                        0.0
147752 2017-01-09  1483974128            ...                             1                        0.0
89983  2017-01-10  1484075970            ...                            10                 39990000.0
87705  2017-01-11  1484170311            ...                            13                 59990000.0

[20 rows x 6 columns]

In [18]:
df_test_sample = load_data('test', n=1)

In [19]:
df_test_sample.head()

  channelGrouping       date         ...         Date_Is_year_end  Date_Is_year_start
0  Organic Search 2018-05-11         ...                    False               False
1          Direct 2018-05-11         ...                    False               False
2  Organic Search 2018-05-11         ...                    False               False
3          Direct 2018-05-11         ...                    False               False
4  Organic Search 2018-05-11         ...                    False               False

[5 rows x 53 columns]

# 調べたいこと

- visitNumberとtotal_transactionRevenueの関係
- geoNetworkと売り上げの関係
- trafficSourceと売り上げの関係
    - 広告経由での売り上げ
- customDimensionsと売り上げの関係